-- MySQL Script generated by MySQL Workbench
-- Sun Sep 29 14:29:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` CHAR(20) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id` INT NOT NULL,
  `name` CHAR(20) NOT NULL,
  `signin` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Guest` (
  `id` INT NOT NULL,
  `event` INT NOT NULL,
  `balance` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `guest-event_idx` (`event` ASC) VISIBLE,
  CONSTRAINT `guest-users`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `guest-event`
    FOREIGN KEY (`event`)
    REFERENCES `mydb`.`Event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Goods` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `event` INT NULL,
  `buyer` INT NULL,
  `price` INT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `goods-event_idx` (`event` ASC) VISIBLE,
  INDEX `goods-guest_idx` (`buyer` ASC) VISIBLE,
  CONSTRAINT `goods-event`
    FOREIGN KEY (`event`)
    REFERENCES `mydb`.`Event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `goods-guest`
    FOREIGN KEY (`buyer`)
    REFERENCES `mydb`.`Guest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
